# Generated by Django 4.2.7 on 2023-12-02 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_favoritos_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritos',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='API.usuarios'),
        ),
    ]
