# Generated by Django 4.2.7 on 2023-12-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yugiohapp', '0002_alter_usuarios_data_cadastro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='img_perfil',
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
