# Generated by Django 5.0 on 2023-12-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yugiohapp', '0002_favorito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorito',
            name='usuario',
            field=models.CharField(max_length=255),
        ),
    ]
