# Generated by Django 4.2.7 on 2023-12-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yugiohapp', '0003_remove_usuarios_img_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
